title: Andrew Sinclair
email: andrew.george.sinclair@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the homepage of Andrew G. Sinclair.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Andy_CDandy
github_username:  AndrewSinclair

theme: minima #jekyll-theme-cayman
